version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - app_network
    restart: unless-stopped

  python_server:
    build:
      context: ./python_server
      dockerfile: Dockerfile
    container_name: python_server
    ports:
      - "5000:5000"
    depends_on:
      - mosquitto
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mosquitto_data:
  mosquitto_logs:

networks:
  app_network:
    driver: bridge
